version: '3'

services:
  object-detection-api:
    build: .
    container_name: object-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/static:/app/app/static
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 